### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by HugKitten** [AlSch092/OKPOE#1]
Hey, is the networking proxying code working in this repository? I would enjoy playing around with POE's protocol. Thanks. :)

**Comment by AlSch092** [comment]
Hi HugKitten,

The assembly is up to date, however you need to make a function pointer to the in-game offset for the function that they use to send packets, then call the assembly function with a pointer pointed at the in-game address.

the offset is currently 0x148ED10

Good luck!
