### ISSUE TITLE
How to get updated version?

### ISSUE THREAD

**Issue by slowice** [AlSch092/OKPOE#2]
Hi, how to get the updated version?

**Comment by AlSch092** [comment]
The full/updated version is only available for sale right now as it's being used by people.. the full source will likely be 1500-2000$ once it's complete and has full detection of everything + fluent auto-botting (which might sound expensive at first glance, but is moreso an investment if youre an RMTer). you can add me on discord at xianman#8321 if you want to speak more. a compiled version is being sold at a very affordable price

have a great day
